// Example usage
export const BOOST_COMMENTS = [
  "This will go up!",
  "I love this one!",
  "To the moon!",
  "Diamond hands all the way!",
  "I'm all in!",
  "HODLing strong!",
  "Next big thing!",
  "Easy 10x!",
  "This is the future!",
  "Hold tight, it's pumping!",
  "No stopping this rocket!",
  "Incredible potential!",
  "Best meme coin ever!",
  "Just getting started!",
  "Can't believe how strong this is!",
  "Everyone's talking about it!",
  "FOMO kicking in!",
  "This is insane!",
  "Hold and prosper!",
  "Buckle up, we're going up!",
  "Legends hold!",
  "Get in before it's too late!",
  "Nothing but up from here!",
  "We believe in this!",
  "All aboard the hype train!",
  "Next stop: Mars!",
  "Amazing community!",
  "LFG!",
  "I'm so bullish!",
  "This is a hidden gem!",
  "Ready to blast off!",
  "Still early!",
  "Pumping hard!",
  "Hype is real!",
  "Big things coming!",
  "You don't want to miss this!",
  "Moon mission engaged!",
  "I've never been more excited!",
  "This is the one!",
  "Massive potential!",
  "All signs are go!",
  "It's now or never!",
  "Stacking up more!",
  "This is unstoppable!",
  "True diamond hands coin!",
  "Ready for liftoff!",
  "Everything is aligned for this!",
  "Rockets fueled and ready!",
  "Bullish AF!",
  "No brainer investment!",
  "Future millionaire here!",
  "Hold the line!",
  "Breaking records soon!",
  "This is a wild ride!",
  "Sky's the limit!",
  "Only way is up!",
  "I'm with this 100%!",
  "Can't wait for what's next!",
  "Feeling lucky!",
  "This is the real deal!",
  "Trust the process!",
  "Game changer!",
  "Straight to the top!",
  "To infinity and beyond!",
  "Never selling!",
  "This is so exciting!",
  "Love the energy here!",
  "Pure gold!",
  "Moonshot guaranteed!",
  "Time to celebrate!",
  "Unstoppable force!",
  "Incredible movement!",
  "Life-changing gains!",
  "This is history in the making!",
  "Bigger than anyone expects!",
  "On a rocket ship!",
  "Momentum is crazy!",
  "I've got a good feeling about this!",
  "Going parabolic!",
  "The hype is justified!",
  "This coin has it all!",
  "No one can stop us now!",
  "Community power!",
  "The best is yet to come!",
  "Full speed ahead!",
  "Moon vibes only!",
  "Making waves in the market!",
  "Absolutely unstoppable!",
  "Legit moonshot!",
  "This is the start of something huge!",
  "Never been this confident before!",
  "Straight fire!",
  "Keep holding, it's worth it!",
  "Patience pays off!",
  "Rising like never before!",
  "This coin is a beast!",
  "Everyone wants in on this!",
  "The pump is real!",
  "All-time high incoming!",
  "We're just warming up!",
  "This is what we've been waiting for!",
  "New era for meme coins!",
  "Only legends are holding this!",
  "Moonbound for sure!",
  "It's our time to shine!",
  "Next big wave is here!",
  "I'm riding this all the way!",
  "No FUD can stop us!",
  "This energy is electric!",
  "Too big to ignore!",
  "All eyes on this!",
  "HODL and prosper!",
  "Game on!",
];
