export const NEUTRAL_COMMENTS = [
  "Interesting insights here.",
  "This is worth looking into.",
  "A great find.",
  "Thought-provoking content.",
  "Definitely something to consider.",
  "Fascinating details here.",
  "Worth a moment of your time.",
  "This could be helpful to someone.",
  "Sharing this for awareness.",
  "Relevant information for many.",
  "Hope this helps someone out.",
  "Always good to explore new ideas.",
  "Great example of something impactful.",
  "Encouraging everyone to check this out.",
  "Informative and engaging.",
  "This caught my attention today.",
  "Might be worth your time.",
  "Glad I came across this.",
  "Something to think about.",
  "Interesting perspective shared here.",
  "A solid example of useful info.",
  "Wanted to share this with the community.",
  "Keeping this in mind for later.",
  "A good resource for learning.",
  "Worth bookmarking for reference.",
  "Found this to be quite interesting.",
  "Some food for thought here.",
  "This resonated with me today.",
  "Sharing this for those interested.",
  "Valuable takeaways from this.",
  "Adding this to my list of must-read content.",
  "Eye-opening in many ways.",
  "A unique perspective presented here.",
  "Glad someone shared this.",
  "A quick look at something relevant.",
  "Offering this as a potential solution.",
  "A good resource to keep handy.",
  "For those who want to dive deeper.",
  "Something I found helpful recently.",
  "This might interest someone.",
  "Offering this to the group.",
  "Passing this along for awareness.",
  "A concise yet valuable read.",
  "A small but powerful piece of content.",
  "This could be a game-changer for some.",
  "A light yet impactful read.",
  "For those interested in learning more.",
  "A gentle reminder to stay curious.",
  "Sharing knowledge is powerful.",
  "A small yet meaningful addition to your day.",
  "Always learning something new.",
  "Every day brings new opportunities.",
  "Curiosity keeps us growing.",
  "Staying informed is key.",
  "Worth exploring further.",
  "Happy to share what I found.",
  "Taking a moment to reflect on this.",
  "Sharing in the spirit of collaboration.",
  "Glad to contribute this to the conversation.",
  "A neutral take on something impactful.",
  "This may offer some value to you.",
  "Found this helpful and thought you might too.",
  "Adding this to the collective knowledge pool.",
  "Sharing for those who might find it useful.",
  "Sometimes small insights make big impacts.",
  "Hope someone finds this interesting.",
  "Letting this speak for itself.",
  "Came across this and had to share.",
  "Always worth considering new perspectives.",
  "Every idea has the potential to grow.",
  "A small nudge towards curiosity.",
  "Learning never stops.",
  "This caught my attention recently.",
  "Happy to share what’s on my mind.",
  "Keeping an open mind about this.",
  "A thoughtful read for anyone interested.",
  "Offering this without expectations.",
  "Knowledge grows when shared.",
  "Every bit of info counts.",
  "Found this worth a second look.",
  "Sharing in the spirit of curiosity.",
  "Learning is a journey, not a destination.",
  "A piece of content that made me think.",
  "For those interested in similar topics.",
  "Every little bit helps expand our thinking.",
  "Sharing this as part of a broader conversation.",
  "Curiosity leads to new ideas.",
  "This could resonate with someone.",
  "Small insights lead to big ideas.",
  "This is something to ponder.",
  "Leaving this here for those interested.",
  "An interesting point worth considering.",
  "Hope this sparks curiosity.",
  "Valuable and neutral information.",
  "A reminder to stay curious and open-minded.",
  "Simple yet meaningful thoughts.",
];

/**
 * Generates neutral, ban-safe comments.
 * @param {string} [website] - Optional website URL to append.
 * @returns {string[]} - Array of neutral comments.
 */
export function getNeutralComments(website?: string) {
  return website
    ? NEUTRAL_COMMENTS.map((comment) => comment + " " + website)
    : NEUTRAL_COMMENTS;
}
