/**
 * Replaces the placeholder [YourWebsiteURL] with the provided website URL.
 * @param {string} website - The website URL to use in the comments.
 * @returns {string[]} - Array of 100 comments with the website URL.
 */
export function getPromoteComments(website: string) {
  const PROMOTE_COMMENTS = [
    "Check this out:",
    "Don't miss this:",
    "See more here:",
    "Explore now:",
    "Discover this:",
    "More info here:",
    "Find out more:",
    "This is amazing:",
    "You'll love this:",
    "Must-see:",
    "Check it now:",
    "Learn more:",
    "See why here:",
    "Get details:",
    "Don't miss out:",
    "Amazing stuff here:",
    "Have you seen this?:",
    "You need to check this out:",
    "Great opportunity here:",
    "Unmissable link:",
    "Don't wait, click here:",
    "This is worth your time:",
    "Worth checking out:",
    "Click here to explore:",
    "You've got to see this:",
    "Get in on this now:",
    "This is next level:",
    "You'll love what's here:",
    "Don't miss what's trending:",
    "Top find here:",
    "Worth a look:",
    "You'll be impressed:",
    "What are you waiting for?:",
    "This is going viral:",
    "Click to find out more:",
    "It's all happening here:",
    "See what everyone's talking about:",
    "Click to explore:",
    "More at this link:",
    "Everyone's checking this out:",
    "This is big:",
    "Great things happening here:",
    "This will blow your mind:",
    "Check the link:",
    "Top-notch content here:",
    "Unmissable opportunity:",
    "Don't skip this:",
    "You won't regret clicking this:",
    "Intriguing stuff here:",
    "Highly recommended:",
    "This is pure gold:",
    "See what's trending now:",
    "The link you've been looking for:",
    "Get in on the buzz:",
    "Hurry, check it out now:",
    "This is the real deal:",
    "Click now, thank me later:",
    "Find out what the fuss is about:",
    "Take a look here:",
    "This will surprise you:",
    "Too good to miss:",
    "The next big thing:",
    "This is catching everyone's eye:",
    "The future starts here:",
    "A must-see link:",
    "Your next stop is here:",
    "Discover the magic:",
    "Find the answers here:",
    "Everything you need is here:",
    "Take a look, it's worth it:",
    "Don't scroll past this:",
    "Find the best here:",
    "This is the talk of the town:",
    "Great vibes here:",
    "Your moment starts here:",
    "Start exploring now:",
    "Feel the energy here:",
    "Next-level experience awaits:",
    "Discover the difference:",
    "Unique and amazing content:",
    "Experience it now:",
    "Something special is here:",
    "Take a closer look:",
    "You've never seen this before:",
    "Make your move now:",
    "Click to unlock greatness:",
    "Exclusive content here:",
    "Don't wait, dive in now:",
    "This is your sign to click:",
    "Time to explore greatness:",
    "New and exciting things here:",
    "This will make your day:",
    "Stop everything and click:",
    "Exceptional stuff here:",
    "See why it's a big deal:",
    "Dive into something new:",
    "Your adventure starts here:",
  ];

  return PROMOTE_COMMENTS.map((comment) => comment + " " + website);
}

// Example usage
const website = "https://example.com";
const promoteComments = getPromoteComments(website);
console.log(promoteComments);
